spring:
  datasource:
    schema:
    - classpath:db/1. schema.sql
    data:
    - classpath:db/2. data.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    sql-script-encoding: UTF-8 

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 1MB

server:
  port: 8080
  servlet:
    encoding:
      force-response: true

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%4line]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n%wEx'
  level:
    root: info
    com.ask: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

setting:
  upload-dir: ~/DEV/upload
  common-error-page: error/error
  server-url: 'http://localhost:${server.port}'