spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      encoding: UTF-8
      schema-locations:
        - classpath:db/1. schema.sql
      data-locations:
        - classpath:db/2. data.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 1MB

server:
  port: 8080
  servlet:
    encoding:
      force-response: true

logging:
  level:
    "[com.ask.sample]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type.descriptor.sql.BasicBinder]": trace

setting:
  upload-dir: ~/DEV/upload
  common-error-page: error/error
  server-url: 'http://localhost:${server.port}'
  jwt-secret: JWT-SECRET